# Generated by Django 4.2.11 on 2024-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("task_path", models.CharField(max_length=255)),
                ("interval_seconds", models.IntegerField(default=60)),
                ("args", models.JSONField(default=list)),
            ],
        ),
    ]
