# Generated by Django 4.2.11 on 2024-04-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="scheduledtask", name="args",),
        migrations.AddField(
            model_name="scheduledtask",
            name="redbeat_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
